# Project information
site_name: 玩转力扣
site_url: https://yanglr.github.io/leetcode
site_author: geekzl
site_description: >-
  极客学长的leetcode刷题笔记
# Repository
repo_name: yanglr/leetcode
repo_url: https://github.com/yanglr/leetcode

# Copyright
copyright: Copyright &copy; 2021 极客学长

theme:
  name: null
  language: 'zh'  
  custom_dir: !ENV [THEME_DIR, "material"]

  # 404 page
  static_templates:
    - 404.html

  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  icon:
    logo: logo

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.highlight:
      linenums: true      
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde  

# Page tree
nav:
  - 主页: index.md
  - 简介:
    - 入门: getting-started.md
  - 算法基础:
    - 算法基础简介: algo/introduction.md
    - 数组: algo/array.md
  - 编程笔记:
    - C++: coding/cpp.md
    - C#: coding/csharp.md    
  - leetcode:
    - leetcode题解: solutions/index.md
    - 玩转力扣Tips: solutions/tips.md
    - leetcode1 两数之和[简单]: solutions/leetcode1 两数之和[简单].md        
    - leetcode4 寻找两个正序数组的中位数[困难]: solutions/leetcode4 寻找两个正序数组的中位数[困难].md 
    - leetcode36 有效的数独[中等]: solutions/leetcode36 有效的数独[中等].md
    - leetcode38 外观数列(报数)[中等]: solutions/leetcode38 外观数列(报数)[中等].md
    